# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://JoaquinRives.github.io/nbdev_minmotion_filters/"

git_url = "https://github.com/JoaquinRives/nbdev_minmotion_filters/tree/"main"/"

def custom_doc_links(name): return None
