# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_shape_and_magnitude_pca_filter.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'