# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_zero_crossing_detector.ipynb (unless otherwise specified).

__all__ = ['say_hello']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'